# Generated by Django 5.2.1 on 2025-06-04 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_expense_income"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="car",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenses",
                to="core.car",
            ),
        ),
        migrations.AddField(
            model_name="income",
            name="car",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="incomes",
                to="core.car",
            ),
        ),
        migrations.AlterField(
            model_name="income",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
